---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-7

suites:
  - name: console
    run_list:
      - recipe[nexpose::default]
    attributes:

  - name: engine
    run_list:
      - recipe[nexpose::default]
    attributes:
      nexpose:
        component_type: engine
